python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh triangle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh circle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh square -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.7 -sh rectangle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh triangle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh circle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh square -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.8 -sh rectangle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh triangle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh circle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh square -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 0.9 -sh rectangle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 0 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 0 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 1 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 1 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 2 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 2 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 3 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 3 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 4 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 4 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 5 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 5 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 6 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 6 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 7 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 7 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 8 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 8 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh triangle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh circle -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh square -tg 3 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 0 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 1 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 2 -r 9 -t release
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 9 -t grasp
python3 goal_infer.py -s 0.6 -tr 1 -sh rectangle -tg 3 -r 9 -t release
